# Site settings
title: Marcus Osterberg CV
description: Marcus Osterberg CV
favicon:
baseurl: /resume/
url: 
rss_url:

# Build settings
markdown: kramdown

# Author settings
author:
  name: Marcus Ã–sterberg
  title: Aspiring full-stack JavaScript developer
  address: Munich, Germany
  email: marcusterberg@gmail.com
  link: omarcusosterberg.com
  github: osterbergmarcus
  twitter: osterbergmarcus
  gavatar:
  workHistory:
    - work1:
      company: Gonutri
      location: Munich, Germany
      title: Co-founder, CTO
      started: 2015
      duration: (2015 - Present)
      description: Gonutri is an innovative platform that connects clients with their nutritionists. My biggest challenge for this project has been to  develop a web app that provides real time communication for our users.
  languages:
    - language1:
      name: Swedish
      proficiency: Native
    - language2:
      name: Norweigan
      proficiency: Professional
    - language3:
      name: Danish
      proficiency: Professional
    - language3:
      name: English
      proficiency: Professional
    - language3:
      name: German
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: JavaScript
    - skill1:
      name: HTML
    - skill1:
      name: CSS
    - skill1:
      name: PHP
    - skill2:
      name: jQuery, vuejs, Polymer-project, Bootstrap, WordPress
